### ISSUE TITLE
模块 ""mand-mobile-next"" 没有导出的成员 "InputItem"

### ISSUE THREAD

**Issue by zihanoo** [mand-mobile/mand-mobile-next#104]
import { InputItem } from 'mand-mobile-next'
![image](https://user-images.githubusercontent.com/8462466/125577243-909e5f12-0a58-4698-99b9-e57db0f11a0c.png)

mand-mobile.d.ts里面也没有相关的import
![image](https://user-images.githubusercontent.com/8462466/125577355-08fc03ba-8ed4-4fed-a6d6-ea812b66be4a.png)

**Comment by zouhangwithsweet** [comment]
升级到 `0.0.1-alpha.2` 试试 :)

**Comment by zihanoo** [comment]
> 升级到 `0.0.1-alpha.2` 试试 :)

已正常，3q
