### ISSUE TITLE
真心地，你们自己有用过这个项目按照文档操作过吗？一堆的bug

### ISSUE THREAD

**Issue by zihanoo** [mand-mobile/mand-mobile-next#117]
https://mand-mobile.github.io/mand-mobile-next/zh-CN/components/scroll-view.html

例如这个。。
import { ScrollView, ScrollViewRefresh, ScrollViewMore } from 'mand-mobile-next'
是错误的，ScrollViewRefresh, ScrollViewMore 并没有导出

例子里面却是
import MdScrollView, {
  PullDown,
  PullUp,
} from 'mand-mobile/scroll-view'
import { ref } from 'vue'

也是错的。。。。

太多太多了。。。

**Comment by zouhangwithsweet** [comment]
首先非常抱歉，文档是根据2.0 版本修改而来，受限与本人精力和工作安排，没有做全部的一一校对，所以一直在alpha的状态当中。因此比较依赖社区的反馈，所以使用方法以 demo 为准。但是，本人一定会及时修复所有问题。社区反馈的越多，我修复的进度也会越快，感谢理解

**Comment by zouhangwithsweet** [comment]
> https://mand-mobile.github.io/mand-mobile-next/zh-CN/components/scroll-view.html
> 
> 例如这个。。
> import { ScrollView, ScrollViewRefresh, ScrollViewMore } from 'mand-mobile-next'
> 是错误的，ScrollViewRefresh, ScrollViewMore 并没有导出
> 
> 例子里面却是
> import MdScrollView, {
> PullDown,
> PullUp,
> } from 'mand-mobile/scroll-view'
> import { ref } from 'vue'
> 
> 也是错的。。。。
> 
> 太多太多了。。。

`import { ScrollView, PullDown, PullUp } from 'mand-mobile-next'` 即可
