### ISSUE TITLE
DatePicker 时间选择器 custom 时错误

### ISSUE THREAD

**Issue by zihanoo** [mand-mobile/mand-mobile-next#120]
https://mand-mobile.github.io/mand-mobile-next/zh-CN/components/date-picker.html

参数设为：
      type="custom"
      :custom-types="['yyyy', 'MM']"

时，发生滑动无法高亮，返回的时间也是错误的。。

另外，该部分文档里面

custom-types
--
自定义类型包含的日期元素, [yyyy, MM, dd, hh, mm, ss]
应该是：['yyyy', 'MM', 'dd', 'hh', 'mm', 'ss']

**Comment by zihanoo** [comment]
![image](https://user-images.githubusercontent.com/8462466/127792915-7bc962e8-e81a-421e-9819-784d5705c5c4.png)

type="custom"
:custom-types="['yyyy', 'MM']"

确信已修复了吗？
"mand-mobile-next": "0.0.1-alpha.7"
效果如如上，无法高亮，确定后输出数据为NaN

@zouhangwithsweet

**Comment by eeeeelle** [comment]
0.0.1-alpha.8 版本已修复，辛苦升级看看~ 
type为custom类型时，由于自定义日期列，选中后不一定是有效的日期类型，所以v-model只能输入数组，具体可参考文档和demo~

**Comment by zihanoo** [comment]
> 0.0.1-alpha.8 版本已修复，辛苦升级看看~
> type为custom类型时，由于自定义日期列，选中后不一定是有效的日期类型，所以v-model只能输入数组，具体可参考文档和demo~


升级为0.0.1-alpha.8后。。
参数为
type="custom"
:custom-types="['yyyy', 'MM']"裂开
![image](https://user-images.githubusercontent.com/8462466/127809533-c4df91ba-2b7c-44b5-bcc5-916c89a4c6f2.png)

**Comment by eeeeelle** [comment]
你好，请看下用法，custom时需要传入数组类型，应该有warning提示 [Mand-Mobile]: v-model should be array when date picker type is custom

**Comment by zihanoo** [comment]
v-model修改为array已经正常了，谢谢

另外：
数据类型错误时，并没有你所说的错误

![image](https://user-images.githubusercontent.com/8462466/127843562-625a45f4-bf27-4e4e-92a7-8eec67bb3735.png)
![image](https://user-images.githubusercontent.com/8462466/127843731-ed340417-8ae4-4168-affb-ce1801c0d368.png)

![image](https://user-images.githubusercontent.com/8462466/127843519-6c707e04-34bc-4133-988a-799005bb8631.png)

**Comment by zihanoo** [comment]
统一的接口规范，还是蛮重要的，目前custom就需要改掉v-model的数据类型，特别不友好

**Comment by zihanoo** [comment]
> 你好，请看下用法，custom时需要传入数组类型，应该有warning提示 [Mand-Mobile]: v-model should be array when date picker type is custom

v-model传入数据为['2021', '9']或者[2021, 9]都无法使得日期有默认选中

@eeeeelle

![image](https://user-images.githubusercontent.com/8462466/127864010-321c5bcc-b99a-4b8b-b77e-0f897f97d7d2.png)

**Comment by eeeeelle** [comment]
有可以复现的demo吗，贴一下使用的参数？

**Comment by zihanoo** [comment]
> 有可以复现的demo吗，贴一下使用的参数？

已经解决，是个人使用过程中，重复赋值了一个空[]导致。
目前已正常，谢谢 @eeeeelle

**Comment by zihanoo** [comment]
有木有可以加一个 '全部' 的项，做一个参数开关来是否使用这个‘全部’的功能
例如：
2021     全部
              1月
              2月
////
另外，可不可以提供一个用户自己写里面的数据，框架只提供这种滑动选择的picker

@eeeeelle @zouhangwithsweet
