### ISSUE TITLE
swiper缺乏indexChange方法

### ISSUE THREAD

**Issue by zihanoo** [mand-mobile/mand-mobile-next#133]
老版本还有goto的。。这个next就完全木有切换跳转到某一个slide的方法。
看到原码里面有个indexChange但是没有暴露出来

**Comment by zouhangwithsweet** [comment]
着急的话，现在可以拿到 swiper instance 调用 BS scroll的原生方法，我倒是可以给包装一下

**Comment by zihanoo** [comment]
> 着急的话，现在可以拿到 swiper instance 调用 BS scroll的原生方法，我倒是可以给包装一下

目前是使用getSwiperInstance能拿到BS scroll解决问题
mySwiper.value.getSwiperInstance()?.goToPage(2, 0)
