### ISSUE TITLE
scroll-view加载数据等待时间低于500ms时，会无法isfinished

### ISSUE THREAD

**Issue by zihanoo** [mand-mobile/mand-mobile-next#134]
https://mand-mobile.github.io/mand-mobile-next/zh-CN/components/scroll-view.html
就用官方的例子就能重现，只要将pullingUpHandler里面的
`
    await sleep(3000)
`
修改为
`
    await sleep(300)
`
就能重现。。。。能一直往上拉，一直能加载
有时600ms都能重现。。。。。

。。。。
无语。。。

**Comment by zouhangwithsweet** [comment]
晚点我看下
