### ISSUE TITLE
0.0.1-alpha.12 import "effectScope" 错误

### ISSUE THREAD

**Issue by zihanoo** [mand-mobile/mand-mobile-next#140]
0.0.1-alpha.12就错误，还原0.0.1-alpha.11正常

![image](https://user-images.githubusercontent.com/8462466/129878959-0c979165-1446-4743-9f95-7ed77f05b360.png)

dependencies
    "vue": "^3.0.5",
    "vue-i18n": "^9.1.6",
    "vue-lottie": "^0.2.1",
    "vue-lottie-ts": "^0.1.2",
    "vue-router": "^4.0.10",
    "vuex": "^4.0.2",
    "vuex-persistedstate": "^4.0.0-beta.3"
devDependencies
    "@types/node": "^16.0.0",
    "@types/qs": "^6.9.6",
    "@typescript-eslint/eslint-plugin": "^4.28.1",
    "@typescript-eslint/parser": "^4.28.1",
    "@vitejs/plugin-vue": "^1.2.4",
    "@vue/compiler-sfc": "^3.0.5",
    "autoprefixer": "^10.3.1",
    "eslint": "^7.30.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-define-config": "^1.0.9",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-vue": "^7.12.1",
    "postcss-pxtorem": "^6.0.0",
    "prettier": "^2.3.2",
    "sass": "^1.35.2",
    "sass-loader": "^12.1.0",
    "stylus": "^0.54.8",
    "stylus-loader": "^6.1.0",
    "typescript": "^4.3.4",
    "vite": "^2.4.2",
    "vite-plugin-components": "^0.13.2",
    "vite-plugin-importer": "^0.2.5",
    "vite-plugin-style-import": "^1.1.1",
    "vue-tsc": "^0.0.24"

**Comment by zouhangwithsweet** [comment]
升级vue到3.2；
https://v3.vuejs.org/api/effect-scope.html#effect-scope-api

**Comment by zihanoo** [comment]
> 升级vue到3.2；
> https://v3.vuejs.org/api/effect-scope.html#effect-scope-api

谢谢，升级3.2后正常了
