### ISSUE TITLE
移动端兼容性问题

### ISSUE THREAD

**Issue by dotcombbbb** [mand-mobile/mand-mobile-next#147]
按照文档做了一个ActionBar 的demo，在PC端预览暂时没问题，使用手机预览会出现一片空白，组件没用被渲染的情况

测试如下：
IOS 系统版本12.5.2  系统自带浏览器无法渲染组件
鸿蒙系统（华为P30），系统自带浏览器正常，微信浏览器，企业微信浏览器无法渲染
安卓（小米10） 系统自带浏览器正常， 企业微信浏览器无法渲染

**Comment by zouhangwithsweet** [comment]
- [ ] 确认浏览器是否支持 vue3 `proxy` 
- [ ] 本组件库打包的 target 为 `ESnext`，在构建项目面向较老的浏览器，最好再次编译一遍该组件库的源码。
   - `vue-cli` 中的 [`transpileDependencies`](https://cli.vuejs.org/config/#transpiledependencies)
   - `vite` 中的 [浏览器兼容性](https://cn.vitejs.dev/guide/build.html#browser-compatibility)
