### ISSUE TITLE
官方文档按需加载vite.config.ts配置有误

### ISSUE THREAD

**Issue by zihanoo** [mand-mobile/mand-mobile-next#91]
文档路径错误

`
          return `mand-mobile-next/dist/es/${name}.scss`;
`
实际
`
          return `mand-mobile-next/dist/es/${name}/index.css`;
`

![image](https://user-images.githubusercontent.com/8462466/125013695-dbadff00-e09e-11eb-9b0c-c165179bd5d3.png)

**Comment by zouhangwithsweet** [comment]
好的，马上修改
